# Generated by Django 3.2.5 on 2021-07-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20210729_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='linkedin',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='frontpage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture/'),
        ),
    ]
